services:
  - type: web
    name: fra-atlas-frontend
    plan: free
    env: node
    buildCommand: |
      npm install
      npm run build:css
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: OCR_API_URL
        sync: true   # Set this after backend deploy, or update on Render dashboard

  - type: web
    name: fra-ocr-api
    plan: free
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr libtesseract-dev poppler-utils libjpeg-dev zlib1g-dev libtiff-dev libfreetype6-dev
      pip install --upgrade pip
      pip install -r OCR/requirements.txt
    startCommand: cd OCR && gunicorn --bind 0.0.0.0:$PORT flask_ocr_api:app
    healthCheckPath: /api/health
    envVars:
      - key: GEMINI_API_KEY
        sync: true
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: DB_FILE
        value: /tmp/fra_claims.db
