services:
  - type: web
    name: fra-ocr-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile  # or path to your Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: GEMINI_API_KEY
        sync: true
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: DB_FILE
        value: /tmp/fra_claims.db
